### PR TITLE
feature/command-line-arguments

### PR DESCRIPTION
**Pull request by eosram**

### CODE REVIEW

**Comment by eosram** [comment]
I wrapped a main function around the code and now it is considerably less clean. I'm not very happy with it. Taking into account the future development of post processing it could be a practicable solution though. Or I could split up the main function? Outsource the post processing into it's own function.  What do you think?

**Comment by ckaldemeyer** [comment]
Hey,

it looks already quite progressed, I think!

Here are some thoughts:

1. Should we just remove the stopwatch (requirement for datetime-package) or put it in oemof-logging anyway? I don't think if it makes sense..
2. Should we pass the files explicitly e.g. nodes=nodes,csv nodes_flows=nodes_flows.csv? And do you use uppercase to distinguish between args and options?
3. We should remove the Spyder cells (#%%) e.g. #%% model creation and solving
4. Should we streamline the logging? It's quite heavy atm..
5. I really don't like the extended renaming section of the dataframe -which is half of the code) and the dataframe as it is now. But that's one for the next version.. :)
6. What do you think about renaming the main-function of renpassgis (some_name(**kw))? 

In general I would keep it really lean and self-explaining!

Should we aim at releasing on Wednesday? I am quite busy with our project atm. and tomorrow we have some meetings..

**Comment by simnh** [comment]
What do you think about having some functionalities (create nodes, postprocessing etc) in own functions and then call them all in main. This would be similar to the app.py file from https://github.com/znes/HESYSOPT, which I took from the old renpass version.  
It would also allow to easily use these functions with 'normal' python scripting.

**Comment by ckaldemeyer** [comment]
> What do you think about having some functionalities (create nodes, postprocessing etc) in own functions and then call them all in main. This would be similar to the app.py file from https://github.com/znes/HESYSOPT, which I took from the old renpass version.
It would also allow to easily use these functions with 'normal' python scripting.

Sounds good to me.

Generally, finding this "lean common app structure" including pre-/postprocessing for oemof is on my TODO list.

This would be a good start I guess..

**Comment by eosram** [comment]
Hey,

thanks, I like the way HESYSOPT app.py is structured and will follow your approach!

**Pull request merged**
