### PR TITLE
Features/generic postprocessing

### LINKED ISSUE #19: Remove label specific result processing

### PR DESCRIPTION
**Pull request by eosram**
resolves #19

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
From the code it looks right! Thanks!

But I don't have time to test it now... Have you checked if it works correctly?

**Comment by ckaldemeyer** [comment]
And should we just integrate the bugfix with the colons (:) in the file names according to @soenkebohm experiences

**Comment by ckaldemeyer** [comment]
?

**Comment by eosram** [comment]
Structure of CSV-files before and after the change is the same. It seems to work. I merge it back then. 
Yes, I think that's a good idea. Do we need an issue for that?

**Comment by ckaldemeyer** [comment]
> Do we need an issue for that?

No, I would just change it directly.

It should be done with something like `datetime.now().strftime("%Y-%m-%d %H-%M")`

Could you do it?

**Comment by soenkebohm** [comment]
So far, I have a quick-and-dirty version in which colons are replaced by dashes. Your suggestion seems to make much more sense, though. Any change here might however affect post-processing procedures (e.g. Marion?) if they refer to results csv files. So would this be a feature for a new model version?

**Comment by ckaldemeyer** [comment]
> So far, I have a quick-and-dirty version in which colons are replaced by dashes. Your suggestion seems to make much more sense, though. Any change here might however affect post-processing procedures (e.g. Marion?) if they refer to results csv files. So would this be a feature for a new model version?

Yes, I would say that this means a new release tag which we need anyway because of the result processing.

@s3pp , what do you think?

**Comment by eosram** [comment]
I agree. This should be part of a new release tag imo! I will change the date format on the dev branch then.

**Comment by ckaldemeyer** [comment]
> I agree. This should be part of a new release tag imo! I will change the date format on the dev branch then.

Thanks!

**Pull request merged**
